language: ruby
cache:
  bundler: true
rvm:
- 2.4.0
before_install:
- bundle install
script:
- "./deploy.sh"
branches:
  only:
  - master
env:
  global:
    secure: "OuKzqMteGtFZCs5pEa6vSFiBvXRFGfGK2Po+VJ21WWI3JwDmsmguG/5+gRNQW5wRXynGxhnVpnpyJAIWOABJHoqGtrsvnf8cQxBM82Ap7H8z6tYUwPWsxuGxu32IE3yipbTl0YOxkYDvLIXbHtS8dUAXMrHNHhkbXWNhsm2UCWYwZsRODoii25dubOKbZz/VtknuQiRdEN9M5NOD+6L9OHO2GOypxSKQ5ip10R7p/H/8A1ndl3eJDlw1d8e5Fin6SVKo6r2Maw3BVqH3Aexo9rDlzn3FiopHEInHyPVk/RfDqC0w+nPSj4R2iYlCW+G3m2lAD4oGMeOIbybZWqndSY5oyNyFWFUP2JC2qoWROs0qt9LvCzYDisgAlex2QG9UKROKh0rJXQG4PPrYXhIgFSzSAWqNN0x+QwG6HdnnlqnZrol3MsG1jeJoMx7gKd78AhQepSRBOcOmMuzC66wrijngJzdm2vV5fHdzyUpQjE1GtoZIWVL6rIKq9Zy82FbkV7Z07Chu+eRw0GmHlBcGJgX+GF2o7D9U6d4wJS5CGhoqsVyRUHfhx0vIz+LjbUR+jDEXMr585QFtkIaNJojfoDj8uQBdaugNJt0u/5RgysBdOK+DqbCsjKy1Z6gsiMNH7YgcY7tBx8oNuBp/R8kdEc276G6YMMW4uzpbf0K2tW0
